name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装依赖并构建
      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist # 指定构建产物目录

      # 发布 GitHub Pages
      - name: Publish GitHub Pages
        uses: actions/deploy-pages@v1
